#!/bin/csh
set tdir=~/archive
set month=`date -u +%Y%b`
set time=`date -u +%d%H%M`
foreach file ($*)
        mkdir -p ${tdir}/${month} >& /dev/null
        set target=${file:r}
        set target=${target:t}
        mkdir -p ${tdir}/${month}/${target} >& /dev/null
  if (-e ${file}) then
    cp ${file} ${tdir}/${month}/${target}/${time}.gif
  endif
end
