#! /bin/csh

#
# Set Up Local Variables
#

#set mdl=a
set mdl=thin
set dt=${1}
set cycle=${2}
rm ${mdl}_meta_out

set device=nc

#set grid=${HDS}/${dt}${cycle}_${mdl}.gem
set grid=/data/gempak/model/gfs/${dt}${cycle}_${mdl}.gem

gdplot_nc << EOF > "$mdl"_meta_out
GDFILE	= $grid
GDATTIM	= FALL
DEVICE	= $device
PANEL	= 0
TEXT	= 1/21//hw
CONTUR	= 1
MAP	    = 1
CLEAR	= yes
CLRBAR  = 1

GAREA	= 17;-122;53;-60
PROJ	= lcc/25;-95;25
LATLON	= 0

restore /home/meteor_ldm/nawips/gempak/nts/nawips/pmsl_thkn.nts
TITLE	= 5/-2/~GFS ^  MSL PRESSURE, 1000-500 MB THICKNESS|^ MSLP, 1000-500 THKN!0
l
ru


restore /home/meteor_ldm/nawips/gempak/nts/nawips/850mb_hght_tmpc.nts
TITLE	= 5/-2/~GFS ^  @  HGHTS, TEMPERATURE AND WIND (KTS)|^ @ HGHT, TMP, WIND!0!0!0
l
ru


restore /home/meteor_ldm/nawips/gempak/nts/nawips/700mb_hght_relh_omeg.nts
TITLE	= 5/-2/~GFS ^  @  HGHTS, REL HUMIDITY AND OMEGA|^ @ HGHT, RH AND OMEGA!0
l
ru


restore /home/meteor_ldm/nawips/gempak/nts/nawips/500mb_hght_absv.nts
TITLE	= 5//~GFS ^  @  HEIGHTS AND VORTICITY|^ @ HGHT AND VORTICITY!0
l
ru


restore /home/meteor_ldm/nawips/gempak/nts/nawips/250mb_hght_wnd.nts
TITLE	= 5/-2/~GFS ^  @  HEIGHTS, ISOTACHS AND WIND (KTS)|^ @ HGHT AND WIND!0
l
ru


restore /home/meteor_ldm/nawips/gempak/nts/nawips/p06m_pmsl.nts
GDATTIM	= F06-F48
TITLE	= 5//~GFS ^  6-HOUR TOTAL PCPN, MSLP|^ 6-HOURLY TOTAL PCPN, MSLP!0
l
ru


restore /home/meteor_ldm/nawips/gempak/nts/nawips/precip.nts
GDATTIM	= F12-F48-6
HILO    = 31;0/x#2//10//y
HLSYM   = 1.5
GFUNC	= (quo(p12m,25.4))
TITLE	= 5//~GFS ^ 12-HOUR TOTAL PRECIPITATION (IN)|^ 12-HOURLY TOTAL PCPN
l
ru


restore /home/meteor_ldm/nawips/gempak/nts/nawips/precip.nts
GDATTIM	= F24-F48-12
HILO    = 31;0/x#2//10//y
HLSYM   = 1.5
GFUNC	= (quo(p24m,25.4))
TITLE	= 5//~GFS ^ 24-HOUR TOTAL PRECIPITATION (IN)|^ 24-HOURLY TOTAL PCPN
l
ru


restore /home/meteor_ldm/nawips/gempak/nts/nawips/precip.nts
GDATTIM	= F48
HILO    = 31;0/x//10//y
HLSYM   = 1.5
GFUNC	= (quo(p48m,25.4))
TITLE	= 5//~GFS ^ 48-HOUR TOTAL PRECIPITATION (IN)|^ 48-HOUR TOTAL PCPN
l
ru


exit
EOF


if ( $device == "nc" ) then

	mv Nmeta $NTRANS_META/gfs/"$mdl"_"$dt"_"$cycle"

endif
