#! /bin/csh
source ~/nawips/Gemenviron
#
# Set Up Local Variables
#

#set mdl=e1
set mdl=ecmf1
set dt=${1}
set cycle=${2}
rm ${mdl}_meta_out

set device=nc

#set grid=${HDS}/${dt}${cycle}_${mdl}.gem
set grid=/data/gempak/model/ecmwf/${dt}${cycle}_${mdl}.gem

gdplot_nc << EOF > "$mdl"_meta_out
GDFILE	= $grid
GDATTIM	= FALL
DEVICE	= $device
PANEL	= 0
TEXT	= 1/21//hw
CONTUR	= 1
MAP	    = 1
CLEAR	= yes
CLRBAR  = 1

GAREA	= 0;-132;60;-25
PROJ	= lcc/30;-95;30
LATLON	= 0

restore /home/nawips/nawips/gempak/nts/nawips/pmsl_thkn.nts
TITLE	= 5/-2/~ECMWF ^ 500mb HGHT & MSL PRESSURE|^ 500mb HGHT & MSLP
GFUNC   = hght@500 !sm5s(pmsl)
l
ru


restore /home/nawips/nawips/gempak/nts/nawips/850mb_hght_tmpc.nts
TITLE	= 5/-2/~ECMWF ^  @  TEMPERATURE |^ @ TMP
l
ru



exit
EOF


if ( $device == "nc" ) then

	mv Nmeta $NTRANS_META/ecmwf/"$mdl"_"$dt"_"$cycle"

endif
