#! /bin/csh
source ~/nawips/Gemenviron
#
# Set Up Local Variables
#

set mdl=mrf201
set dt=${1}
set cycle=${2}
rm ${mdl}_meta_out

set device=nc

set grid=/data/gempak/model/mrf/${dt}${cycle}_${mdl}.gem

gdplot_nc << EOF > "$mdl"_meta_out
GDFILE	= $grid
GDATTIM	= FALL
DEVICE	= $device
PANEL	= 0
TEXT	= 1/21//hw
CONTUR	= 1
MAP	    = 1
CLEAR	= yes
CLRBAR  = 1

GAREA	= 0;-132;60;-25
PROJ    = lcc/30;-95;30
LATLON	= 0

restore /home/nawips/nawips/gempak/nts/nawips/pmsl_thkn.nts
TITLE	= 5/-2/~MRF ^  500mb HGHTS & MSL PRESSURE|^ 500mb HGHT & MSLP
l
ru



exit
EOF


if ( $device == "nc" ) then

	mv Nmeta $NTRANS_META/mrf/"$mdl"_"$dt"_"$cycle"

endif
