#! /bin/csh 
########################################################
# Script for plotting forecasts from current day's ETA
# model to ps for conversion to gif and display on web.  
#
# Can be run from cron.
# Invoke with 1 argument: 00 or 12 for the model run 
# 
########################################################
#
# source the 5.2 environment variables 
#
source /nawips/Gemenviron
#
# cd to temporary directory. This is where the ps file 
# will be placed
#
cd www
#
# Define current date
#
set yy=`date -u +%y`
set mm=`date -u +%m`
set dd=`date -u +%d`
set date=${yy}${mm}${dd}
#
# Set up local variables
#
# DATA_DIR=GEMPAK gridded data directory;
# META_DIR=Directory to store Meta files in
# LOGFILE=file to catch GEMPAK program output
#
setenv DATA_DIR	/data/gempak/hrs
setenv LOGFILE 	www
#
# Remove last hour's eta ps plot and www file
#
# /bin/rm -f ps.plt_eta
# /bin/rm -f www_eta
#
# above made redundant by mv below...

#
# Set some variables for GDPLOT run
#
set device="INVGPS|||C|P"
#set grid=${DATA_DIR}/${date}${1}.gbm
set grid=${DATA_DIR}/${date}${1}_eta.gem
#
# Run GDPLOT and generate ETA model gfs
#
$GEMEXE/gdplot << EOF >> $LOGFILE
\$RESPOND = YES
GDFILE	= $grid
GDATTIM	= f36
DEVICE	= $device 
PANEL	= 0
TEXT	= 1.2/21//hw
CONTUR	= 1
MAP     = 31
CLEAR	= yes
CLRBAR  = 31

GAREA	= grid
PROJ	= lcc/25;-95;25
LATLON	= 0

GLEVEL  = 0:10000          !8400:9800                ! 3000:0
GVCORD  = sgma             !sgma             !hght
GFUNC   = (quo(pwtr,25.4)) !lft4              !helc
GVECT   =
CINT    = .5;.75;1.0;1.25;1.5;1.75;2.0!-14.;-12.;-10.;-8.;-6.;-4.;-2.;0.;2.!150.;250.;300.;400.;600.
LINE    = 0               !15/1/2          ! 30/5/2
TITLE   = 5// ~ ETA  PWTR,LI AND HELICITY    |^ PREC.WATER, LI, HELICITY  !0
SCALE   = 0
SKIP    = 0
FINT    = .5;.75;1.0;1.25;1.5;1.75;2.0
FLINE   = 0;21-25;28-30;14;15;2;5
CTYPE   = c/f                !c                ! c
HILO    =                  !                 !
HLSYM   =
list
run


exit
EOF
#
# Run GPEND to clean up
#
$GEMEXE/gpend
# Copy ps.plt to different name for eta model
#mv ps.plt ps.plt_eta
mv ps.plt /webpix/eta2s.ps
mv www www_eta2s
#
#endif


