#! /bin/csh
# 13 Mar 2003	Cleanups

source ~/webscripts/COMMON

setenv LOGFILE  www_egrr
rm -f www_egrr ukmet.gif

set device="GF|ukmet.gif"
set grid=/data/gempak/model/ukmet/${DATE}${1}_ukmet.gem
#
# Run GDPLOT and generate AVN model gfs
#
$GEMEXE/gdplot_gf << EOF >> $LOGFILE
\$RESPOND = YES
GDFILE  = $grid
GDATTIM = f12-f72-12
DEVICE  = $device
PANEL   = 0
TEXT    = 1.2/21//hw
CONTUR  = 1
MAP     = 31/1/1
CLEAR   = yes
CLRBAR  = 31

GAREA   = 13;-129;60;-45
PROJ    = lcc/25;-95;25
LATLON  = 0

GLEVEL  = 500:1000                  !0
GVCORD  = pres                      !none
GFUNC   = (sub(hght@500,hght@1000)) !pmsl@0%none
SCALE   = -1                        !0
CINT    = 6                         !4
LINE    = 3/3/1                     !20//2
GVECT   =
TITLE   = 5/-2/ ~ UKMET MSL PRESSURE, 1000-500 MB THICKNESS|^ MSLP, 1000-500 THKN!0
SKIP    = 1
FINT    =
FLINE   =
CTYPE   = c
HLSYM   = 2;1.5//21//hw
HILO    = ! 25;2/H#;L#///30;30/y
STNPLT  = 0
\$mapfil=HIPOWO.GSF
list
run


exit
EOF
#
# Run GPEND to clean up
#
# Copy ps.plt to different name for eta model
if (-e ukmet.gif) then

  cp ukmet.gif ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_MSLP_1000_500mb_Thickness_f12.gif
  cp ukmet.gif.001 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_MSLP_1000_500mb_Thickness_f24.gif
  cp ukmet.gif.002 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_MSLP_1000_500mb_Thickness_f36.gif
  cp ukmet.gif.003 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_MSLP_1000_500mb_Thickness_f48.gif
  cp ukmet.gif.004 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_MSLP_1000_500mb_Thickness_f60.gif
  cp ukmet.gif.005 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_MSLP_1000_500mb_Thickness_f72.gif

  mv ukmet.gif     ukmet_01.gif
  mv ukmet.gif.001 ukmet_02.gif
  mv ukmet.gif.002 ukmet_03.gif
  mv ukmet.gif.003 ukmet_04.gif
  mv ukmet.gif.004 ukmet_05.gif
  mv ukmet.gif.005 ukmet_06.gif
  keep ukmet_0[1-6].gif 
  mv ukmet_0[1-6].gif /webpix
endif
#
# Run GDPLOT and generate AVN model gfs
#
$GEMEXE/gdplot_gf << EOF >> $LOGFILE
\$RESPOND = YES
GDFILE  = $grid
GVCORD  = pres
GLEVEL  = 500
GVECT   = WND !
WIND    = bk31/0.9
SKIP    = /2;2 !
GFUNC   = (avor(OBS))           !(avor(obs))           !hght
CINT    = 2/10/99               !2/4/8                 !6
LINE    = 7/5/1/2               !4/5/1/2               !19/1/2/1
HILO    = 2;6/X;N/10-99;10-99   !
SCALE   = 5                     !5                     ! -1
TITLE   = 5/-2/ ~ UKMET 500 HEIGHTS AND VORTICITY|^ 500 HGHT AND VORTICITY!0
PROJ    = lcc/25;-95;25/1,3,0,0
FINT    = 16;20;24;28;32;36;40;44
FLINE   = 0;23-15
CTYPE   = c/f ! c
STNPLT  = 0
\$mapfil=HIPOWO.GSF
list
run

exit
EOF
#
# Run GPEND to clean up
#
# Copy ps.plt to different name for eta model
if (-e ukmet.gif) then
 
  cp ukmet.gif ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_500mb_heights_vorticity_f12.gif
  cp ukmet.gif.001 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_500mb_heights_vorticity_f24.gif
  cp ukmet.gif.002 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_500mb_heights_vorticity_f36.gif
  cp ukmet.gif.003 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_500mb_heights_vorticity_f48.gif
  cp ukmet.gif.004 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_500mb_heights_vorticity_f60.gif
  cp ukmet.gif.005 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_500mb_heights_vorticity_f72.gif

  mv ukmet.gif ukmet_07.gif
  mv ukmet.gif.001 ukmet_08.gif
  mv ukmet.gif.002 ukmet_09.gif
  mv ukmet.gif.003 ukmet_10.gif
  mv ukmet.gif.004 ukmet_11.gif
  mv ukmet.gif.005 ukmet_12.gif
  keep ukmet_0[7-9].gif ukmet_1[0-2].gif
  mv ukmet_0[7-9].gif ukmet_1[0-2].gif /webpix
endif

# Run GDPLOT and generate AVN model gfs
#
$GEMEXE/gdplot_gf << EOF >> $LOGFILE
\$RESPOND = YES
GDFILE  = $grid
GDATTIM = F12-F72-12
SCALE   = 0 !0 ! ! 3
GLEVEL  = 0 ! 0 ! 0 ! 700
GVCORD  = pres !pres  !none !pres
GFUNC   = (quo(p06m,25.4)) !(quo(p06m,25.4)) ! pmsl@0%none !omeg@700%pres
GVECT   =
CINT    = /.1/.1!0.10;0.25;0.50;0.75;1.0;1.25;1.5;1.75;2.0;2.25;2.50;2.75;3.0!4!4
LINE    = 20//1/0           !30//1/0          ! 5/1/1/3 !2/1/1/1
TITLE   = 5/-2/ ~ UKMET 06-HR TOTAL PCPN, MSLP, 700 VV|^ 06-HRLY TOT PCPN, MSLP, 700 VV!0!0
SKIP    = 0
FINT    = 0.05;0.10;0.25;0.50;0.75;1.0;1.25;1.5;1.75;2.0;2.25;2.50;2.75;3.0
FLINE   = 0;21-27;24;28-30;14;15;2;5
CTYPE   = f                !f                !c  !c
HILO    =                  !                 !25;2////30;30/y !
HLSYM   = 2;1.5//21//hw
STNPLT  = 0
\$mapfil=HIPOWO.GSF
list
run

exit
EOF
#
# Run GPEND to clean up
#
# Copy ps.plt to different name for eta model
#mv ps.plt ps.plt_eta
if (-e ukmet.gif) then
 
  
  cp ukmet.gif ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_6hr_precip_MSLP_700VV_f12.gif
  cp ukmet.gif.001 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_6hr_precip_MSLP_700VV_f24.gif
  cp ukmet.gif.002 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_6hr_precip_MSLP_700VV_f36.gif
  cp ukmet.gif.003 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_6hr_precip_MSLP_700VV_f48.gif
  cp ukmet.gif.004 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_6hr_precip_MSLP_700VV_f60.gif
  cp ukmet.gif.005 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_6hr_precip_MSLP_700VV_f72.gif

  mv ukmet.gif ukmet_13.gif
  mv ukmet.gif.001 ukmet_14.gif
  mv ukmet.gif.002 ukmet_15.gif
  mv ukmet.gif.003 ukmet_16.gif
  mv ukmet.gif.004 ukmet_17.gif
  mv ukmet.gif.005 ukmet_18.gif
  keep ukmet_1[3-8].gif 
  mv ukmet_1[3-8].gif /webpix
endif
