#! /bin/csh
# 31 Mar 2003	First time here

source ~/webscripts2/COMMON
#
setenv DATA_DIR $MODEL
setenv LOGFILE  www_egrr2
rm -f www_egrr2 ukmet2.gif
set device="GF|ukmet2.gif"
set grid=${DATA_DIR}/ukmet/${DATE}${1}_ukmet.gem
#
# Run GDPLOT and generate UKMET model gfs
#
$GEMEXE/gdplot_gf << EOF >> $LOGFILE
\$RESPOND = YES
GDFILE  = $grid
GDATTIM = f12-f72-12
DEVICE  = $device
PANEL   = 0
TEXT    = 1.2/21//hw
CONTUR  = 1
MAP     = 31/1/1
CLEAR   = yes
CLRBAR  = 31

GAREA   = 15;-129;60;-45
PROJ    = lcc/25;-95;25
LATLON  = 0

GLEVEL  = 850                      !850 !850
GVCORD  = pres                     !pres!pres
GFUNC   = dwpc                     !hght!tmpc
SCALE   = 0                        ! 0 !0
CINT    = -20;-16;-12;-8;-4;0;4;8;10;12;14;16;18;20  ! 30 !5
LINE    = 7/5/1/2                  ! 2/1/2/1 !32/5/2/2
GVECT   = WND
WIND    = bk4/0.9
TITLE   = 5/-2/ ~ UKMET  850 HGHTS, DEW POINTS, T (C) AND WIND|^ 850 Z, TD, T, WIND!0
SKIP    = /1;1 !
FINT    = -20;-16;-12;-8;-4;0;4;8;10;12;14;16;18;20
FLINE   = 27;26-16--1;14-8--2 !
CTYPE   = f ! c !c
HLSYM   =
HILO    =
STNPLT  = 0
\$mapfil=HIPOWO.GSF
list
run


exit
EOF
#
# Run GPEND to clean up
# Copy ps.plt to different name for eta model

cp ukmet2.gif ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_850mb_heights_T_Td_winds_f12.gif
cp ukmet2.gif.001 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_850mb_heights_T_Td_winds_f24.gif
cp ukmet2.gif.002 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_850mb_heights_T_Td_winds_f36.gif
cp ukmet2.gif.003 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_850mb_heights_T_Td_winds_f48.gif
cp ukmet2.gif.004 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_850mb_heights_T_Td_winds_f60.gif
cp ukmet2.gif.005 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_850mb_heights_T_Td_winds_f72.gif

mv ukmet2.gif ukmet2_01.gif
mv ukmet2.gif.001 ukmet2_02.gif
mv ukmet2.gif.002 ukmet2_03.gif
mv ukmet2.gif.003 ukmet2_04.gif
mv ukmet2.gif.004 ukmet2_05.gif
mv ukmet2.gif.005 ukmet2_06.gif
###mv ukmet2.gif.006 ukmet2_06.gif
keep ukmet2_0[1-6].gif 
mv ukmet2_0[1-6].gif /webpix
#
# Run GDPLOT and generate ETA model gfs
#
$GEMEXE/gdplot_gf << EOF >> $LOGFILE
\$RESPOND = YES
GAREA   = 15;-129;60;-45
PROJ    = lcc/25;-95;25
CLRBAR  = 31

GLEVEL  = 700
GVCORD  = pres !pres !pres
GFUNC   = relh(tmpc,dwpc)    !tmpc           !hght
GVECT   = wnd  ! !
WIND    = bk2/0.8
skip    = /1;1 !
CINT    = 10;30;50;70;90 !-20;-10;-5;0;4;6;8;10;12;14;16;18   !30
LINE    = 7/5/1/2               !32/2/2/1             !4/1/2/2
HLSYM   =
HILO    =
SCALE   = 0  !0 !0
TITLE   = 5/-2/ ~ UKMET 700 HEIGHTS, RH and TEMP|^ 700 HGHT, RH AND TEMP!0!0
FINT    = 10;30;50;70;90
FLINE   = 15;11;17-23-2
CTYPE   = f ! c
STNPLT  = 0
\$mapfil=HIPOWO.GSF
list
run

exit
EOF
#
# Run GPEND to clean up
#
# Copy ps.plt to different name for eta model

cp ukmet2.gif ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_700mb_heights_RH_Temps_f12.gif
cp ukmet2.gif.001 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_700mb_heights_RH_Temps_f24.gif
cp ukmet2.gif.002 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_700mb_heights_RH_Temps_f36.gif
cp ukmet2.gif.003 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_700mb_heights_RH_Temps_f48.gif
cp ukmet2.gif.004 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_700mb_heights_RH_Temps_f60.gif
cp ukmet2.gif.005 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_700mb_heights_RH_Temps_f72.gif

mv ukmet2.gif ukmet2_07.gif
mv ukmet2.gif.001 ukmet2_08.gif
mv ukmet2.gif.002 ukmet2_09.gif
mv ukmet2.gif.003 ukmet2_10.gif
mv ukmet2.gif.004 ukmet2_11.gif
mv ukmet2.gif.005 ukmet2_12.gif
keep ukmet2_0[7-9].gif ukmet2_1[0-2].gif
mv ukmet2_0[7-9].gif ukmet2_1[0-2].gif /webpix

# Run GDPLOT and generate AVN model gfs
#
$GEMEXE/gdplot_gf << EOF >> $LOGFILE
\$RESPOND = YES
GAREA   = 15;-129;60;-45
PROJ    = lcc/25;-95;25
CLRBAR  = 31

GLEVEL  = 250
GVCORD  = pres !pres  !pres
GFUNC   = sped !hght  !div(wnd)
GVECT   = ! !
CINT    = 10;20;30;40;50;60;70;80;90! 120 !2
LINE    = 7/5/1/2           !31/1/2/2  !29/1/1/1
TITLE   = 5/-2/ ~ UKMET 250 MB HGHTS, WIND SPEED (M/S) AND DIV|^ 250 MB HGHTS, SPEEDS, DIV!0!
SCALE   = 0 ! 0 ! 5
SKIP    = 0 ! 0 ! 0
FINT    = 10;20;30;40;50;60;70;80;90!!
FLINE   = 0;26-16--2;14-8--2
CTYPE   = f              !c
HLSYM   =
HILO    =
STNPLT  = 0
\$mapfil=HIPOWO.GSF
list
run

exit
EOF
#
# Run GPEND to clean up
# Copy ps.plt to different name for eta model
#mv ps.plt ps.plt_eta

cp ukmet2.gif ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_250mb_heights_winds_DIV_f12.gif
cp ukmet2.gif.001 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_250mb_heights_winds_DIV_f24.gif
cp ukmet2.gif.002 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_250mb_heights_winds_DIV_f36.gif
cp ukmet2.gif.003 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_250mb_heights_winds_DIV_f48.gif
cp ukmet2.gif.004 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_250mb_heights_winds_DIV_f60.gif
cp ukmet2.gif.005 ${ddir2}/pix/ukmet/${1}z/ukmet_${DATE}${1}_250mb_heights_winds_DIV_f72.gif

mv ukmet2.gif ukmet2_13.gif
mv ukmet2.gif.001 ukmet2_14.gif
mv ukmet2.gif.002 ukmet2_15.gif
mv ukmet2.gif.003 ukmet2_16.gif
mv ukmet2.gif.004 ukmet2_17.gif
mv ukmet2.gif.005 ukmet2_18.gif
keep ukmet2_1[3-8].gif 
mv ukmet2_1[3-8].gif /webpix
#
#endif


