#! /bin/csh 

source ~/webscripts/COMMON
setenv DATA_DIR	/data/gempak/mos
setenv LOGFILE 	www_mos
rm -f www_mos mos.gif
set device="GF|mos.gif"
set date1=`date --date '24 hours' +'%Y%m%d'`
set date2=`date --date '48 hours' +'%Y%m%d'`
set grid=${DATA_DIR}/${DATE}${1}_nmos.gem
#
# Run SFMAP to generate plot of 12hrly temps,qpf,pp
#
$GEMEXE/sfmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE	= $device
AREA     = 39.5;-98;45;-88
GAREA    = 39.5;-98;45;-88
SATFIL   = 
RADFIL   = 
STNPLT   =   
SFPARM   = tdyf
DATTIM   = ${date1}/00
SFFILE   = $grid
COLORS   = (0-100-10/29-7--2/tdyf)
MAP      = 15/1/3
LATLON   = 0
MARKER   = 0
TITLE    = 31/-2/~  NGM MOS DAYTIME TEMPERATURE
CLEAR    = yes
PANEL    = 0
PROJ     = lcc
FILTER   = 0.8
TEXT     = 0.70/2/1/hw
SKPMIS   = NO
list
run


exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
##if (-e mos_01.gif) then
  mv mos.gif /webpix/mos_01.gif
  keep /webpix/mos_01.gif
##endif

$GEMEXE/sfmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE	= $device
AREA     = 39.5;-98;45;-88
GAREA    = 39.5;-98;45;-88
SATFIL   = 
RADFIL   = 
STNPLT   =   
SFPARM   = tntf
DATTIM   = ${date1}/12
SFFILE   = $grid
COLORS   = (-20-80-10/29-7--2/tntf)
MAP      = 15/1/3
LATLON   = 0
MARKER   = 0
TITLE    = 31/-2/~  NGM MOS NIGHT TEMPERATURE
CLEAR    = yes
PANEL    = 0
PROJ     = lcc
FILTER   = 0.8
TEXT     = 0.70/2/1/hw
SKPMIS   = NO
list
run


exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
##if (-e mos_01.gif) then
  mv mos.gif /webpix/mos_02.gif
  keep /webpix/mos_02.gif
##endif
$GEMEXE/sfmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE	= $device
AREA     = 39.5;-98;45;-88
GAREA    = 39.5;-98;45;-88
SATFIL   = 
RADFIL   = 
STNPLT   =   
SFPARM   = tdyf
DATTIM   = ${date2}/00
SFFILE   = $grid
COLORS   = (0-100-10/29-7--2/tdyf)
MAP      = 15/1/3
LATLON   = 0
MARKER   = 0
TITLE    = 31/-2/~  NGM MOS DAYTIME TEMPERATURE
CLEAR    = yes
PANEL    = 0
PROJ     = lcc
FILTER   = 0.8
TEXT     = 0.70/2/1/hw
SKPMIS   = NO
list
run


exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
##if (-e mos_01.gif) then
  mv mos.gif /webpix/mos_03.gif
  keep /webpix/mos_03.gif
##endif
$GEMEXE/sfmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE	= $device
AREA     = 39.5;-98;45;-88
GAREA    = 39.5;-98;45;-88
SATFIL   = 
RADFIL   = 
STNPLT   =   
SFPARM   = tntf
DATTIM   = ${date2}/12
SFFILE   = $grid
COLORS   = (-20-80-10/29-7--2/tntf)
MAP      = 15/1/3
LATLON   = 0
MARKER   = 0
TITLE    = 31/-2/~  NGM MOS NIGHT TEMPERATURE
CLEAR    = yes
PANEL    = 0
PROJ     = lcc
FILTER   = 0.8
TEXT     = 0.70/2/1/hw
SKPMIS   = NO
list
run


exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
##if (-e mos_01.gif) then
  mv mos.gif /webpix/mos_04.gif
  keep /webpix/mos_04.gif
##endif
