#! /bin/csh 

source ~/webscripts/COMMON
setenv DATA_DIR	/data/gempak/mos
setenv LOGFILE 	www_mos
rm -f www_mos mos.gif
set device="GF|mos.gif"
set date1=`date --date '24 hours' +'%Y%m%d'`
set date2=`date --date '48 hours' +'%Y%m%d'`
set grid=${DATA_DIR}/${DATE}${1}_nmos.gem
#
# Run SFMAP to generate plot of 12hrly temps,qpf,pp
#
$GEMEXE/sfmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE	= $device
AREA     = 39.5;-98;45;-88
GAREA    = 39.5;-98;45;-88
SATFIL   = 
RADFIL   = 
STNPLT   =   
SFPARM   = tdyf
DATTIM   = ${date1}/00
SFFILE   = $grid
COLORS   = (0-100-10/29-7--2/tdyf)
MAP      = 15/1/3
LATLON   = 0
MARKER   = 0
TITLE    = 31/-2/~  NGM MOS DAYTIME TEMPERATURE
CLEAR    = yes
PANEL    = 0
PROJ     = lcc
FILTER   = 0.8
TEXT     = 0.70/2/1/hw
SKPMIS   = NO
list
run


exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
cp mos.gif ${ddir}${DATE2}/pix/mos/00z/ngm_mos_${DATE}00_daytime_temps_f24.gif
##if (-e mos_01.gif) then
  mv mos.gif /webpix/mos_05.gif
  keep /webpix/mos_05.gif
##endif

$GEMEXE/sfmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE	= $device
AREA     = 39.5;-98;45;-88
GAREA    = 39.5;-98;45;-88
SATFIL   = 
RADFIL   = 
STNPLT   =   
SFPARM   = tntf
DATTIM   = ${date1}/12
SFFILE   = $grid
COLORS   = (-20-80-10/29-7--2/tntf)
MAP      = 15/1/3
LATLON   = 0
MARKER   = 0
TITLE    = 31/-2/~  NGM MOS NIGHT TEMPERATURE
CLEAR    = yes
PANEL    = 0
PROJ     = lcc
FILTER   = 0.8
TEXT     = 0.70/2/1/hw
SKPMIS   = NO
list
run


exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
cp mos.gif ${ddir}${DATE2}/pix/mos/00z/ngm_mos_${DATE}00_nighttime_temps_f36.gif
##if (-e mos_01.gif) then
  mv mos.gif /webpix/mos_06.gif
  keep /webpix/mos_06.gif
##endif
$GEMEXE/sfmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE	= $device
AREA     = 39.5;-98;45;-88
GAREA    = 39.5;-98;45;-88
SATFIL   = 
RADFIL   = 
STNPLT   =   
SFPARM   = tdyf
DATTIM   = ${date2}/00
SFFILE   = $grid
COLORS   = (0-100-10/29-7--2/tdyf)
MAP      = 15/1/3
LATLON   = 0
MARKER   = 0
TITLE    = 31/-2/~  NGM MOS DAYTIME TEMPERATURE
CLEAR    = yes
PANEL    = 0
PROJ     = lcc
FILTER   = 0.8
TEXT     = 0.70/2/1/hw
SKPMIS   = NO
list
run


exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
cp mos.gif ${ddir}${DATE2}/pix/mos/00z/ngm_mos_${DATE}00_daytime_temps_f48.gif
##if (-e mos_01.gif) then
  mv mos.gif /webpix/mos_07.gif
  keep /webpix/mos_07.gif
##endif
$GEMEXE/sfmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE	= $device
AREA     = 39.5;-98;45;-88
GAREA    = 39.5;-98;45;-88
SATFIL   = 
RADFIL   = 
STNPLT   =   
SFPARM   = tntf
DATTIM   = ${date2}/12
SFFILE   = $grid
COLORS   = (-20-80-10/29-7--2/tntf)
MAP      = 15/1/3
LATLON   = 0
MARKER   = 0
TITLE    = 31/-2/~  NGM MOS NIGHT TEMPERATURE
CLEAR    = yes
PANEL    = 0
PROJ     = lcc
FILTER   = 0.8
TEXT     = 0.70/2/1/hw
SKPMIS   = NO
list
run


exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
cp mos.gif ${ddir}${DATE2}/pix/mos/00z/ngm_mos_${DATE}00_nighttime_temps_f60.gif
##if (-e mos_01.gif) then
  mv mos.gif /webpix/mos_08.gif
  keep /webpix/mos_08.gif
##endif
$GEMEXE/sfmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE  = $device
AREA     = 39.5;-98;45;-88
GAREA    = 39.5;-98;45;-88
SATFIL   =
RADFIL   =
STNPLT   =
SFPARM   = pp12
DATTIM   = ${date1}/00
SFFILE   = $grid
COLORS   = (0-100-10/29-7--2/pp12)
MAP      = 15/1/3
LATLON   = 0
MARKER   = 0
TITLE    = 31/-2/~  NGM MOS 12hr Prob of Prec
CLEAR    = yes
PANEL    = 0
PROJ     = lcc
FILTER   = 0.8
TEXT     = 0.70/2/1/hw
SKPMIS   = NO
list
run
                                                                                            
                                                                                            
exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
cp mos.gif ${ddir}${DATE2}/pix/mos/00z/ngm_mos_${DATE}00_12hr_pops_f24.gif
##if (-e mos_01.gif) then
  mv mos.gif /webpix/mos_05p.gif
  keep /webpix/mos_05p.gif
##endif

$GEMEXE/sfmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE  = $device
AREA     = 39.5;-98;45;-88
GAREA    = 39.5;-98;45;-88
SATFIL   =
RADFIL   =
STNPLT   =
SFPARM   = pp12
DATTIM   = ${date1}/12
SFFILE   = $grid
COLORS   = (0-100-10/29-7--2/pp12)
MAP      = 15/1/3
LATLON   = 0
MARKER   = 0
TITLE    = 31/-2/~  NGM MOS 12hr Prob of Prec
CLEAR    = yes
PANEL    = 0
PROJ     = lcc
FILTER   = 0.8
TEXT     = 0.70/2/1/hw
SKPMIS   = NO
list
run
                                                                                            
                                                                                            
exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
cp mos.gif ${ddir}${DATE2}/pix/mos/00z/ngm_mos_${DATE}00_12hr_pops_f36.gif
##if (-e mos_01.gif) then
  mv mos.gif /webpix/mos_06p.gif
  keep /webpix/mos_06p.gif
##endif
$GEMEXE/sfmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE  = $device
AREA     = 39.5;-98;45;-88
GAREA    = 39.5;-98;45;-88
SATFIL   =
RADFIL   =
STNPLT   =
SFPARM   = pp12
DATTIM   = ${date2}/00
SFFILE   = $grid
COLORS   = (0-100-10/29-7--2/pp12)
MAP      = 15/1/3
LATLON   = 0
MARKER   = 0
TITLE    = 31/-2/~  NGM MOS 12hr Prob of Prec
CLEAR    = yes
PANEL    = 0
PROJ     = lcc
FILTER   = 0.8
TEXT     = 0.70/2/1/hw
SKPMIS   = NO
list
run
                                                                                            
                                                                                            
exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
cp mos.gif ${ddir}${DATE2}/pix/mos/00z/ngm_mos_${DATE}00_12hr_pops_f48.gif
##if (-e mos_01.gif) then
  mv mos.gif /webpix/mos_07p.gif
  keep /webpix/mos_07p.gif
##endif
$GEMEXE/sfmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE  = $device
AREA     = 39.5;-98;45;-88
GAREA    = 39.5;-98;45;-88
SATFIL   =
RADFIL   =
STNPLT   =
SFPARM   = pp12
DATTIM   = ${date2}/12
SFFILE   = $grid
COLORS   = (0-100-10/29-7--2/pp12)
MAP      = 15/1/3
LATLON   = 0
MARKER   = 0
TITLE    = 31/-2/~  NGM MOS 12hr Prob of Prec
CLEAR    = yes
PANEL    = 0
PROJ     = lcc
FILTER   = 0.8
TEXT     = 0.70/2/1/hw
SKPMIS   = NO
list
run
                                                                                            
                                                                                            
exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
cp mos.gif ${ddir}${DATE2}/pix/mos/00z/ngm_mos_${DATE}00_12hr_pops_f60.gif
##if (-e mos_01.gif) then
  mv mos.gif /webpix/mos_08p.gif
  keep /webpix/mos_08p.gif
##endif
$GEMEXE/sfmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE  = $device
AREA     = 39.5;-98;45;-88
GAREA    = 39.5;-98;45;-88
SATFIL   =
RADFIL   =
STNPLT   =
SFPARM   = qp12
DATTIM   = ${date1}/00
SFFILE   = $grid
COLORS   = (0-6-1/29-15--2/qp12)
MAP      = 15/1/3
LATLON   = 0
MARKER   = 0
TITLE    = 31/-2/~  NGM MOS 12hr Prob of Prec
CLEAR    = yes
PANEL    = 0
PROJ     = lcc
FILTER   = 0.8
TEXT     = 0.70/2/1/hw
SKPMIS   = NO
list
run
                                                                                            
                                                                                            
exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
cp mos.gif ${ddir}${DATE2}/pix/mos/00z/ngm_mos_${DATE}00_12hr_QPF_f24.gif
##if (-e mos_01.gif) then
  mv mos.gif /webpix/mos_05q.gif
  keep /webpix/mos_05q.gif
##endif
$GEMEXE/sfmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE  = $device
AREA     = 39.5;-98;45;-88
GAREA    = 39.5;-98;45;-88
SATFIL   =
RADFIL   =
STNPLT   =
SFPARM   = qp12
DATTIM   = ${date1}/12
SFFILE   = $grid
COLORS   = (0-6-1/29-15--2/qp12)
MAP      = 15/1/3
LATLON   = 0
MARKER   = 0
TITLE    = 31/-2/~  NGM MOS 12hr Prob of Prec
CLEAR    = yes
PANEL    = 0
PROJ     = lcc
FILTER   = 0.8
TEXT     = 0.70/2/1/hw
SKPMIS   = NO
list
run
                                                                                            
                                                                                            
exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
cp mos.gif ${ddir}${DATE2}/pix/mos/00z/ngm_mos_${DATE}00_12hr_QPF_f36.gif
##if (-e mos_01.gif) then
  mv mos.gif /webpix/mos_06q.gif
  keep /webpix/mos_06q.gif
##endif
$GEMEXE/sfmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE  = $device
AREA     = 39.5;-98;45;-88
GAREA    = 39.5;-98;45;-88
SATFIL   =
RADFIL   =
STNPLT   =
SFPARM   = qp12
DATTIM   = ${date2}/00
SFFILE   = $grid
COLORS   = (0-6-1/29-15--2/qp12)
MAP      = 15/1/3
LATLON   = 0
MARKER   = 0
TITLE    = 31/-2/~  NGM MOS 12hr Prob of Prec
CLEAR    = yes
PANEL    = 0
PROJ     = lcc
FILTER   = 0.8
TEXT     = 0.70/2/1/hw
SKPMIS   = NO
list
run
                                                                                            
                                                                                            
exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
cp mos.gif ${ddir}${DATE2}/pix/mos/00z/ngm_mos_${DATE}00_12hr_QPF_f48.gif
##if (-e mos_01.gif) then
  mv mos.gif /webpix/mos_07q.gif
  keep /webpix/mos_07q.gif
##endif
$GEMEXE/sfmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE  = $device
AREA     = 39.5;-98;45;-88
GAREA    = 39.5;-98;45;-88
SATFIL   =
RADFIL   =
STNPLT   =
SFPARM   = qp12
DATTIM   = ${date2}/12
SFFILE   = $grid
COLORS   = (0-6-1/29-15--2/qp12)
MAP      = 15/1/3
LATLON   = 0
MARKER   = 0
TITLE    = 31/-2/~  NGM MOS 12hr Prob of Prec
CLEAR    = yes
PANEL    = 0
PROJ     = lcc
FILTER   = 0.8
TEXT     = 0.70/2/1/hw
SKPMIS   = NO
list
run
                                                                                            
                                                                                            
exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
cp mos.gif ${ddir}${DATE2}/pix/mos/00z/ngm_mos_${DATE}00_12hr_QPF_f60.gif
##if (-e mos_01.gif) then
  mv mos.gif /webpix/mos_08q.gif
  keep /webpix/mos_08q.gif
##endif
