#! /bin/csh 
# 03 Mar 2003:	Begin Tracking!!!
# 04 Mar 2003:	Get rid of counties
# 21 Mar 2003	More debugging

source ~/webscripts/COMMON
setenv LOGFILE 	www_proz
rm -f proz1.gif* >& /dev/null

set device="GF|proz1.gif"
# set grid=${DATA_DIR}/${date}${1}.gbm
#set grid=/data/gempak/profiler/${DATE}${1}_pro.gem
set grid=/mtarchive2/data/2007/06/01/gempak/profiler/20070601_pro.gem
#
#
$GEMEXE/snmap_gf << EOF > $LOGFILE
\$RESPOND = YES
DEVICE	= GF|proz1.gif|740;540
AREA     = 29;-105;46;-83
GAREA    = 29;-105;46;-83
SATFIL   = /data/mcidas/AREA0144
RADFIL   = /data/nexrad/BREF1/12/9704181215.DMX
SNPARM   = brbk
DATTIM   = last
LEVELS   = 800
VCOORD   = hght
SNFILE   = $grid
COLORS   = 6
MAP      = 5
LATLON   = 0
MARKER   = 0
TITLE    = 3/-2/ ~ 800 M WINDS FROM PROFILERS
CLEAR    = yes
PANEL    = 0
PROJ     = lcc
FILTER   = no
TEXT     = 1.1
STNPLT   =  
\$mapfil =
list
run

exit
EOF

exit

#
# Run GPEND to clean up
#
if (-e proz1.gif) then
  cp proz1.gif ${ddir}${DATE2}/pix/pro/800m_winds/${DATE}${hh}_800m_winds.gif
  mv proz1.gif /webpix/proz1.gif
  keep /webpix/proz1.gif
endif

$GEMEXE/snmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE	= GF|proz2.gif|740;540
SNPARM   = brbk
DATTIM   = last
LEVELS   = 1000
VCOORD   = hght
SNFILE   = $grid
TITLE    = 3/-2/ ~ 1000 M WINDS FROM PROFILERS
STNPLT   =  
\$mapfil =
list
run

exit
EOF

#
# Run GPEND to clean up
#
if (-e proz2.gif) then
  cp proz2.gif ${ddir}${DATE2}/pix/pro/1000m_winds/${DATE}${hh}_1000m_winds.gif
  mv proz2.gif /webpix/proz2.gif
  keep /webpix/proz2.gif
endif

$GEMEXE/snmap << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE	= GF|proz3.gif|740;540
SNPARM   = brbk
DATTIM   = last
LEVELS   = 1400
COLORS   = 2
VCOORD   = hght
SNFILE   = $grid
TITLE    = 3/-2/ ~ 850(red),700(yellow),500(cyan)MB PROF. WINDS
STNPLT   =  
\$mapfil =
list
run

SNPARM   = brbk
DATTIM   = last
LEVELS   = 3000
CLEAR    = no
COLORS   = 5
VCOORD   = hght
SNFILE   = $grid
TITLE    = 
STNPLT   =  
\$mapfil =
list
run

SNPARM   = brbk
CLEAR    = no 
DATTIM   = last
COLORS   = 6
LEVELS   = 5600 
VCOORD   = hght
SNFILE   = $grid
TITLE    = 
STNPLT   =  
\$mapfil =
list
run

exit
EOF

#

#
# Run GPEND to clean up
#
$GEMEXE/gpend
#
if (-e proz3.gif) then
  cp proz3.gif ${ddir}${DATE2}/pix/pro/850mb_700mb_500mb_winds/${DATE}${hh}_850_700_500mb_winds.gif
  mv proz3.gif /webpix/proz3.gif
  keep /webpix/proz3.gif
endif
#
$GEMEXE/snmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE	= GF|proz4.gif|740;540
AREA     = 29;-105;46;-83
GAREA    = 29;-105;46;-83
SATFIL   = /data/mcidas/AREA0144
RADFIL   = /data/nexrad/BREF1/12/9704181215.DMX
SNPARM   = brbk
DATTIM   = last
LEVELS   = 9000
VCOORD   = hght
SNFILE   = $grid
COLORS   = 6
MAP      = 5
LATLON   = 0
MARKER   = 0
TITLE    = 3/-2/ ~9000 M (300 MB) WINDS FROM PROFILERS
CLEAR    = yes
PANEL    = 0
PROJ     = lcc
FILTER   = no
TEXT     = 1.1
STNPLT   =  
\$mapfil =
list
run

exit
EOF
#
# Run GPEND to clean up
#
#$GEMEXE/gpend
# Rename ps file to indicate sfc data
if (-e proz4.gif) then
  cp proz4.gif ${ddir}${DATE2}/pix/pro/300mb_winds/${DATE}${hh}_300mb_winds.gif
  mv proz4.gif /webpix/proz4.gif
  keep /webpix/proz4.gif
endif
#mv www www_proz
