#! /bin/csh 
########################################################
# Script for plotting 6am and noon temps for use 
# primarily in MT206 forecast contest
#
# Can be run from cron.
# 
########################################################
#
# source the 5.2 environment variables 
#
source /nawips/Gemenviron
setenv DISPLAY mesonet.agron.iastate.edu:3
#
# Set the root Ntrans directory
#
# setenv NTRANSHOME  ${NAWIPS}/nprogs/ntrans2.1
#
# cd to temporary directory. This is where the Nmeta file 
# will be kept while the script is running.
#
cd ~/webscripts/www
#
# Define current date
#
set yy=`date -u +%y`
set mm=`date -u +%m`
set dd=`date -u +%d`
set date=${yy}${mm}${dd}
# set hh=`date -u +%H`
#
# Set up local variables
#
# DATA_DIR=GEMPAK surface data directory;
# META_DIR=Directory to store Meta files in
# LOGFILE=file to catch GEMPAK program output
#
setenv DATA_DIR	/data/gempak/profiler
setenv LOGFILE 	www_proz
#
# Remove last hour's sfc grid file, and ps file
#
rm -f www_proz proz1.gif
#
# Set some variables for GDPLOT run
#
#set device="invgps|||C|P"
set device="GF|proz1.gif"
# set grid=${DATA_DIR}/${date}${1}.gbm
set grid=${DATA_DIR}/${date}${1}_pro.gem
#
# Run SNMAP to generate horizontal plot of low-level winds
#
$GEMEXE/snmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE	= GF|proz1.gif|740;540
AREA     = 29;-105;46;-83
GAREA    = 29;-105;46;-83
SATFIL   = /data/mcidas/AREA0144
RADFIL   = /data/nexrad/BREF1/12/9704181215.DMX
SNPARM   = brbk
DATTIM   = last
LEVELS   = 800
VCOORD   = hght
SNFILE   = $grid
COLORS   = 6
MAP      = 5
LATLON   = 0
MARKER   = 0
TITLE    = 3/-2/ ~ 800 M WINDS FROM PROFILERS
CLEAR    = yes
PANEL    = 0
PROJ     = lcc
FILTER   = no
TEXT     = 1.1
STNPLT   =  
list
run

exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
mv proz1.gif /webpix/proz1.gif
keep /webpix/proz1.gif
$GEMEXE/snmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE	= GF|proz2.gif|740;540
SNPARM   = brbk
DATTIM   = last
LEVELS   = 1000
VCOORD   = hght
SNFILE   = $grid
TITLE    = 3/-2/ ~ 1000 M WINDS FROM PROFILERS
STNPLT   =  
list
run

exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
mv proz2.gif /webpix/proz2.gif
keep /webpix/proz2.gif
$GEMEXE/snmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE	= GF|proz3.gif|740;540
SNPARM   = brbk
DATTIM   = last
LEVELS   = 1400
VCOORD   = hght
SNFILE   = $grid
TITLE    = 3/-2/ ~ 1400 M WINDS FROM PROFILERS
STNPLT   =  
list
run

exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
mv proz3.gif /webpix/proz3.gif
keep /webpix/proz3.gif
$GEMEXE/snmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE	= GF|proz4.gif|740;540
SNPARM   = brbk
DATTIM   = last
LEVELS   = 3000
VCOORD   = hght
SNFILE   = $grid
TITLE    = 3/-2/ ~ 3000 M (700 MB) WINDS FROM PROFILERS
STNPLT   =  
list
run

exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
mv proz4.gif /webpix/proz4.gif
keep /webpix/proz4.gif
$GEMEXE/snmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE	= GF|proz5.gif|740;540
SNPARM   = brbk
DATTIM   = last
LEVELS   = 5600 
VCOORD   = hght
SNFILE   = $grid
TITLE    = 3/-2/ ~ 5600 M (500 MB) WINDS FROM PROFILERS
STNPLT   =  
list
run

exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
mv proz5.gif /webpix/proz5.gif
keep /webpix/proz5.gif
#mv www www_proz
