#! /bin/csh 
########################################################
#
# Can be run from cron.
# 
########################################################
#
# source the 5.2 environment variables 
#
source /nawips/Gemenviron
#
# Set the root Ntrans directory
#
# setenv NTRANSHOME  ${NAWIPS}/nprogs/ntrans2.1
#
# cd to temporary directory. This is where the Nmeta file 
# will be kept while the script is running.
#
cd www
#
# Define current date
#
set yy=`date -u +%y`
set mm=`date -u +%m`
set dd=`date -u +%d`
set date=${yy}${mm}${dd}
set hh=`date -u +%H`
#
# Set up local variables
#
# DATA_DIR=GEMPAK surface data directory;
# META_DIR=Directory to store Meta files in
# LOGFILE=file to catch GEMPAK program output
#
setenv DATA_DIR	/data/nexrad/BREF1
setenv LOGFILE 	www
#
# Remove last hour's  www file
rm -f www_rad
rm -f gempak.gif
#
# Set some variables for GPMAP run
#
#set device="invgps|||C|P"
set device="GF"
# set grid=${DATA_DIR}/${date}${1}.gbm
set grid=${DATA_DIR}/${hh}/${date}${hh}${1}
set grid1="/data/gempak/surface/sao/"
#
# Run GPMAP to generate radar plot
#
$GEMEXE/gpmap << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE   = $device
MAP      = 5/1/1
GAREA    = dmx*
PROJ     = rad
SATFIL   = 
RADFIL   = ${grid}05.DMX
LATLON   = 0
PANEL    = 0 
#TITLE    = 31/-2/ DES MOINES REFLECTIVITY DATA - ${hh}:10 
TITLE    = 1
TEXT     = 1/2/1/hw
CLEAR    = yes
\$mapfil=hicnus.nws
list
run

MAP      = 21/1/5
CLEAR    = no
\$mapfil=hiponw.cia
list
run

exit
EOF
# Run SFMAP to overlay IDs
#
$GEMEXE/sfmap << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE  = $device
AREA     = ia*
GAREA    = dmx*
SATFIL   =
RADFIL   = ${grid}05.DMX
SFPARM   = stid
DATTIM   = ${date}/${hh}
SFFILE   = ${grid1}${date}.gem
COLORS   = 7
MAP      = 21/1/5
LATLON   = 0
MARKER   = 0
TITLE    = 0
CLEAR    = no
PANEL    = 0
PROJ     = rad
FILTER   = 0.7
TEXT     = 1/2/1/hw
SKPMIS   = NO
list
run

\$mapfil=mepowo.gsf
exit
EOF

#
# Run GPEND to clean up
#
$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
mv gempak.gif /webpix/rad.gif
mv www www_rad
