#! /bin/csh 
# 31 Mar 2003	My first visit
#
source ~/webscripts/COMMON
rm -f satwv.gif
setenv LOGFILE 	www_satwv
set device="GF|satwv.gif|960;720"
set grid=`ls -t /data/mcidas/AREA021? | head -1`
#
$GEMEXE/gpmap_gf << EOF > $LOGFILE
\$RESPOND = YES
DEVICE   = $device
\$mapfil = hipowo.nws
MAP      = 3/1/2
GAREA    = 20;-120;65;-59
PROJ     = sat
SATFIL   = ${grid}
RADFIL   =        
LATLON   = 0
PANEL    = 0 
TITLE    = 1
LUTFIL   = DEFAULT
STNPLT   = 0
TEXT     = 1/2/1/hw
CLEAR    = yes
list
run

exit
EOF

#
# publish and archive the image
mkdir -p ${ddir}${DATE2}/pix/sat/WV/

if ( -e satwv.gif ) then
cp satwv.gif ${ddir}${DATE2}/pix/sat/WV/${DATE}${hh}_WVsat.gif
mv satwv.gif /webpix/satwv.gif
keep /webpix/satwv.gif
endif
