#! /bin/csh 
# 31 Mar 2003	My first visit
#
source ~/webscripts/COMMON
#
set bigdate=`date -u +%Y.%m.%d\ %HZ`
rm -f satvis.gif
setenv LOGFILE 	www_satvis
set device="GF|satvis.gif|960;720"
set grid=`ls -t /data/mcidas/AREA014? | head -1`
set grid1="/data/gempak/surface/sao/"
#
$GEMEXE/gpmap_gf << EOF > $LOGFILE
\$RESPOND = YES
DEVICE   = $device
MAP      = 3/1/2
\$mapfil = hipowo.nws
GAREA    = 20;-120;65;-59
PROJ     = sat
SATFIL   = ${grid}
RADFIL   =        
LATLON   = 0
PANEL    = 0 
TITLE    = 1
LUTFIL   = DEFAULT
STNPLT   = 0
TEXT     = 1/2/1/hw
CLEAR    = yes
list
run

exit
EOF

#
# publish and archive the image
mkdir -p  ${ddir}${DATE2}/pix/sat/VIS/

if ( -e satvis.gif ) then
cp satvis.gif ${ddir}${DATE2}/pix/sat/VIS/${DATE}${hh}_VISsat.gif
mv satvis.gif /webpix/satvis.gif
keep /webpix/satvis.gif
endif
