#! /bin/csh 
# 31 Mar 2003	My first time here!

source ~/webscripts/COMMON
rm -f satir.gif
setenv LOGFILE 	www_satir
#
set device="GF|satir.gif|960;720"
set grid=`ls -t /data/mcidas/AREA015? | head -1`
#
$GEMEXE/gpmap_gf << EOF > $LOGFILE
\$RESPOND = YES
DEVICE   = $device
\$mapfil = hipowo.nws
MAP      = 3/1/2
GAREA    = 20;-120;65;-59
PROJ     = sat
SATFIL   = ${grid}
RADFIL   =        
LATLON   = 0
PANEL    = 0 
TITLE    = 1
LUTFIL   = /disk2a/nawips/gempak5.4/tables/luts/coldlut.tbl
STNPLT   = 0
TEXT     = 1/2/1/hw
CLEAR    = yes
list
run

exit
EOF

#
if (-e satir.gif) then
 cp satir.gif ${ddir}${DATE2}/pix/sat/IR/${DATE}${hh}_IRsat.gif
 mv satir.gif /webpix/satir.gif
 keep /webpix/satir.gif
endif
