#! /bin/csh 
#
source ~/webscripts/COMMON
setenv LOGFILE 	www_skewf
#
# Remove last hour's sfc grid file, and ps file
#
rm -f www_skewf
#
# Set some variables for GDPLOT run
#
set device="gf"
# set grid=${DATA_DIR}/${date}${1}.gbm
set grid=/data/gempak/model/${DATE}00_eta211.gem
#
# Run GDPROF to generate skew-Ts for AMW
#
$GEMEXE/gdprof << EOF >> $LOGFILE
DEVICE   = GF|skewf_01.gif
GPOINT   = 42;-93.7
GDATTIM  = f24
GVCORD   = pres
GFUNC    = tmpc
GVECT    = wnd
GDFILE   = $grid
LINE     = 3/1/1
MARKER   = 0
BORDER   = 31
PTYPE    = skewt
SCALE    = 0
XAXIS    = -40/40/10/1;1;1
YAXIS    = 1020/100/100/1;1;1
WIND     = bk27/.8/1//.5
REFVEC   = 
WINPOS   = 1
FILTER   = no
TITLE    = 5/-0/ ~ SKEW-T (12HR) PREDICTION FOR AMES, IA
PANEL    = 0
CLEAR    = yes
TEXT     = 1.2
DEVICE   = xw
OUTPUT   = t
THTALN   = 4/1/1
THTELN   = 5/2/1
MIXRLN   = 2/2/1
list
run



GFUNC    = dwpc
CLEAR    = no
THTALN   = 
THTELN   = 
MIXRLN   = 
list
run


exit
EOF

#
# Run GPEND to clean up
#
$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
mv skewf_01.gif /webpix/skewf_01.gif

$GEMEXE/gdprof << EOF >> $LOGFILE
DEVICE   = GF|skewf_02.gif
GPOINT   = 42;-93.7
GDATTIM  = f48
GVCORD   = pres
GFUNC    = tmpc
GVECT    = wnd
GDFILE   = $grid
LINE     = 3/1/1
MARKER   = 0
BORDER   = 31
PTYPE    = skewt
SCALE    = 0
XAXIS    = -40/40/10/1;1;1
YAXIS    = 1020/100/100/1;1;1
WIND     = bk27/.8/1//.5
REFVEC   = 
WINPOS   = 1
FILTER   = no
TITLE    = 5/-0/ ~ SKEW-T (36HR) PREDICTION FOR AMES, IA
PANEL    = 0
CLEAR    = yes
TEXT     = 1.2
DEVICE   = xw
OUTPUT   = t
THTALN   = 4/1/1
THTELN   = 5/2/1
MIXRLN   = 2/2/1
list
run



GFUNC    = dwpc
CLEAR    = no
THTALN   = 
THTELN   = 
MIXRLN   = 
list
run


exit
EOF

#
# Run GPEND to clean up
#
$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
mv skewf_02.gif /webpix/skewf_02.gif
