#! /bin/csh 
########################################################
# Script for plotting 6am and noon temps for use 
# primarily in MT206 forecast contest
#
# Can be run from cron.
# 
########################################################
#
# source the 5.2 environment variables 
#
source /nawips/Gemenviron
setenv DISPLAY mesonet.agron.iastate.edu:3
#
# Set the root Ntrans directory
#
# setenv NTRANSHOME  ${NAWIPS}/nprogs/ntrans2.1
#
# cd to temporary directory. This is where the Nmeta file 
# will be kept while the script is running.
#
cd www
#
# Define current date
#
set yy=`date -u +%y`
set mm=`date -u +%m`
set dd=`date -u +%d`
set date=${yy}${mm}${dd}
# set hh=`date -u +%H`
#
# Set up local variables
#
# DATA_DIR=GEMPAK surface data directory;
# META_DIR=Directory to store Meta files in
# LOGFILE=file to catch GEMPAK program output
#
setenv DATA_DIR	/data/gempak/upperair
setenv LOGFILE 	www
#
# Remove last hour's sfc grid file, and ps file
#
rm -f www_skew
#
# Set some variables for GDPLOT run
#
set device="invgps|||C|P"
# set grid=${DATA_DIR}/${date}${1}.gbm
set grid=${DATA_DIR}/${date}_upa.gem
#
# Run SNPROF to generate skew-Ts from OAX and DVN
#
$GEMEXE/snprof << EOF >> $LOGFILE
SNFILE   = $grid
DEVICE	= $device 
DATTIM   = ${dd}/${1}
AREA     = @oax
SNPARM   = tmpc;dwpc
LINE     = 3
PTYPE    = skewt
VCOORD   = pres
STNDEX   = lift;swet;kinx;totl;cape;cins;brch
STNCOL   = 15
WIND     = bk27/.8/1//.5
WINPOS   = 1
MARKER   = 0
BORDER   = 31
TITLE    = 5/-0/ SKEW-T FROM OMAHA, NE
YAXIS    = 1020/100//1;1;0
XAXIS    = -40/40/10/1;1;0
FILTER   = no
CLEAR    = yes
PANEL    = 0
TEXT     = 0.8/2//hw
THTALN   = 4/1/1
THTELN   = 4/2/1
MIXRLN   = 2/2/1
list
run

AREA     = @dvn
SNPARM   = tmpc;dwpc
LINE     = 3
PTYPE    = skewt
VCOORD   = pres
STNDEX   = lift;swet;kinx;totl;cape;cins;brch
STNCOL   = 15
WIND     = bk27/.8/1//.5
WINPOS   = 1
MARKER   = 0
BORDER   = 15
TITLE    = 5/-0/ SKEW-T FROM DAVENPORT, IA
YAXIS    = 1020/100//1;1;0
XAXIS    = -40/40/10/1;1;0
FILTER   = no
CLEAR    = yes
PANEL    = 0
TEXT     = 0.8/2//hw
THTALN   = 4/1/1
THTELN   = 4/2/1
MIXRLN   = 2/2/1
list
run

exit
EOF

#
# Run GPEND to clean up
#
$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
mv ps.plt /webpix/skew.ps
mv www www_skew
