#! /bin/csh 
########################################################
# Script for plotting 6am and noon temps for use 
# primarily in MT206 forecast contest
#
# Can be run from cron.
# 
########################################################
#
# source the 5.2 environment variables 
#
source /nawips/Gemenviron
setenv DISPLAY mesonet.agron.iastate.edu:3.0
#
# Set the root Ntrans directory
#
# setenv NTRANSHOME  ${NAWIPS}/nprogs/ntrans2.1
#
# cd to temporary directory. This is where the Nmeta file 
# will be kept while the script is running.
#
cd ~/webscripts/www
#
# Define current date
#
set yy=`date -u +%y`
set mm=`date -u +%m`
set dd=`date -u +%d`
set date=${yy}${mm}${dd}
# set hh=`date -u +%H`
#
# Set up local variables
#
# DATA_DIR=GEMPAK surface data directory;
# META_DIR=Directory to store Meta files in
# LOGFILE=file to catch GEMPAK program output
#
setenv DATA_DIR	/data/gempak/surface/sao
setenv LOGFILE 	www
#
# Remove last hour's sfc grid file, and ps file
#
rm -f www_tmp
#
# Set some variables for GDPLOT run
#
set device="gf"
# set grid=${DATA_DIR}/${date}${1}.gbm
set grid=${DATA_DIR}/${date}${1}.gem
#
# Run SFMAP to generate plot of 6 am temps
#
$GEMEXE/sfmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE	= GF|tmp_01.gif|720;540
AREA     = 20;-128;53;-54
GAREA    = 20;-116;51;-62
SATFIL   = 
RADFIL   = 
STNPLT   =   
SFPARM   = tmpf
DATTIM   = ${dd}/12
SFFILE   = $grid
COLORS   = 5
MAP      = 15/1/3
LATLON   = 0
MARKER   = 0
TITLE    = 31/-2/~  6 AM SURFACE TEMPERATURE
CLEAR    = yes
PANEL    = 0
PROJ     = lcc
FILTER   = 0.8
TEXT     = 0.68/2/1/hw
SKPMIS   = NO
list
run


exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
mv tmp_01.gif /webpix/tmp_01.gif

$GEMEXE/sfmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE	= GF|tmp_02.gif|720;540
AREA     = dset
SATFIL   = 
RADFIL   = 
STNPLT   =  
SFPARM   = p24i
DATTIM   = ${dd}/12
SFFILE   = $grid
COLORS   = 5 
MAP      = 15/1/2
LATLON   = 0
MARKER   = 0
TITLE    = 31/-2/~  24 HR PRECIPITATION (INCHES)
CLEAR    = yes
PANEL    = 0
PROJ     = lcc
FILTER   = 0.55
TEXT     = 0.68/2/1/hw
SKPMIS   = NO
list
run


exit
EOF

#
# Run GPEND to clean up
#
#$GEMEXE/gpend
#
# Rename ps file to indicate sfc data
mv tmp_02.gif /webpix/tmp_02.gif
mv www www_tmp
