#! /bin/csh 
########################################################
# Script for plotting forecasts from current day's ETA
# model to gif for display on web.  Also will plot
# current hour surface data and upper air data
#
# Can be run from cron.
# Invoke with 1 argument: 00 or 12 for the model run 
# 
########################################################
#
# source the 5.2 environment variables 
#
source /nawips/Gemenviron
setenv DISPLAY mesonet.agron.iastate.edu:3.0
#
# Set the root Ntrans directory
#
# setenv NTRANSHOME  ${NAWIPS}/nprogs/ntrans2.1
#
# cd to temporary directory. This is where the Nmeta file 
# will be kept while the script is running.
#
cd ~/webscripts/www
#
# Define current date
#
set yy=`date -u +%y`
set mm=`date -u +%m`
set dd=`date -u +%d`
set date=${yy}${mm}${dd}
#
# Set up local variables
#
# DATA_DIR=GEMPAK surface data directory;
# META_DIR=Directory to store Meta files in
# LOGFILE=file to catch GEMPAK program output
#
setenv DATA_DIR	/data/gempak/hrs
setenv LOGFILE 	www_ua1
#
# Remove last upper grid file and upper ps plot
#
rm -f file3.grd
rm -f ps.plt_ua1
rm -f www_ua1
rm -f ua1_0?.gif >& /dev/null
#
# Set some variables for GDPLOT run
#
set device="GF"
set grid=${DATA_DIR}/${date}${1}_eta.gem
set grid1=/data/gempak/upperair/${date}_upa.gem
#
#
# Run GDPLOT and generate analyzed 300, 200 map
#
# changed 2001.04.13 geff@iastate.edu
#$GEMEXE/gdplot << EOF >> $LOGFILE
$GEMEXE/gdplot_gf << EOF >> $LOGFILE
\$RESPOND = YES
GDFILE	= $grid
GDATTIM	= f00
DEVICE	= GF|ua1_01.gif|720;540
PANEL	= 0
TEXT	= 1/21//hw
CONTUR	= 1
MAP      = 15/1/2
CLEAR	= yes
CLRBAR  = 1

GAREA    = 15;-133;57;-49
PROJ     = lcc/35;-95;20
LATLON   = 0

GLEVEL   = 300
GVCORD   = pres
SKIP     = /6/6
SCALE    = 
GFUNC    = sped    !   hght
CTYPE    = c/f     !   c
CONTUR   = 
CINT     = 25;35;45;55;65;75;85;95      !   120
LINE     = 19/1/1   !   32/1/3
FINT     = 25;35;45;55;65;75;85;95
FLINE    = 27-21--3;18-16--2;14-4--2
HILO     = 
HLSYM    = 2;1.5//21//hw
CLRBAR   = 0
GVECT    =     
WIND     = 0
REFVEC   = 
TITLE    = 31/-2/~ 300 MB HEIGHTS AND WIND SPEEDS (M/S)
TEXT     = 1.0/2//hw
SATFIL   = 
RADFIL   = 
STNPLT   =  
list
run

exit
$GEMEXE/snmap_gf << EOF >> $LOGFILE
\$RESPOND = YES
DEVICE  = GF|ua1_01.gif|720;540
PANEL   = 0
CONTUR  = 1
MAP      = 15/1/2                                                                                      
CLEAR   = yes                                                                                          
CLRBAR  = 1                                                                                            
PROJ     = lcc/35;-95;20                                                                               
LATLON   = 0           
AREA     = 15;-133;57;-49
GAREA    = 15;-133;57;-49
SATFIL   = 
RADFIL   = 
SNPARM   = brbk;tmpc;;stdz;;dpdc
DATTIM   = ${date}/${1}
LEVELS   = 300
VCOORD   = pres
SNFILE   = $grid1
COLORS   = 32
TITLE    =  
CLEAR    = no
FILTER   = no
TEXT     = 0.8/22/2/HW
LUTFIL   =  
STNPLT   = 
 
exit
EOF

#
# Run GPEND to clean up
#
# disabled 2001.04.13 geff@iastate.edu
#$GEMEXE/gpend
#
# Rename ps plot to indicate upper air data
mv ua1_01.gif /webpix/ua1_01.gif
keep /webpix/ua1_01.gif

# changed 2001.04.13 geff@iastate.edu
#$GEMEXE/gdplot << EOF >> $LOGFILE
$GEMEXE/gdplot_gf << EOF >> $LOGFILE
\$RESPOND = YES
GDFILE	= $grid
GDATTIM	= f00
DEVICE	= GF|ua1_02.gif|720;540
GLEVEL   = 200
GVCORD   = pres
SKIP     = /6/6
SCALE    = 
GFUNC    = sped    !   hght
CTYPE    = c/f     !   c
CONTUR   = 
CINT     = 25;35;45;55;65;75;85;95      !   120
LINE     = 19/1/1   !   32/1/3
FINT     = 25;35;45;55;65;75;85;95
FLINE    = 27-21--3;18-16--2;14-4--2
HILO     = 
HLSYM    = 2;1.5//21//hw
CLRBAR   = 0
GVECT    = WND 
WIND     = bk32/0.9/1
REFVEC   = 
TITLE    = 31/-2/~ 200 MB HEIGHTS AND WIND SPEEDS (M/S)
TEXT     = 1.0/2//hw
SATFIL   = 
RADFIL   = 
STNPLT   =  
list
run

exit
EOF

#
# Run GPEND to clean up
#
# disabled 2001.04.13 geff@iastate.edu
#$GEMEXE/gpend
#
# Rename ps plot to indicate upper air data
mv ua1_02.gif /webpix/ua1_02.gif
keep /webpix/ua1_02.gif
